name: Belajar CI Dasar

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World (Github Actions)"

  info-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show System Info
        run: |
            echo "User $(whoami)"
            echo "OS info:"
            uname -a
            
      - name: Force error
        run: exit 1